channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.2
- pip:
  - mlflow==3.8.0
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - pandas==2.3.1
  - scikit-learn==1.7.0
  - scipy==1.16.0
name: mlflow-env
